Nop.Plugin.Misc.FraudLabsPro/Controllers/FraudLabsProController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Orders;
using Nop.Plugin.Misc.FraudLabsPro.Models;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Misc.FraudLabsPro.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class FraudLabsProController : BasePluginController
    {
        #region Fields

        private readonly FraudLabsProSettings _fraudLabsProSettings;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;

        #endregion

        #region Ctor

        public FraudLabsProController(
            FraudLabsProSettings fraudLabsProSettings,
            ILocalizationService localizationService,
            INotificationService notificationService,
            ISettingService settingService
            )
        {
            _fraudLabsProSettings = fraudLabsProSettings;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _settingService = settingService;
        }

        #endregion

        #region Utilities

        /// <summary>
        /// Prepare FraudLabsProModel
        /// </summary>
        /// <param name="model">Model</param>
        protected async Task PrepareModelAsync(ConfigurationModel model)
        {
            //prepare common properties
            model.ApiKey = _fraudLabsProSettings.ApiKey;
            model.ApproveStatusID = _fraudLabsProSettings.ApproveStatusID;
            model.ReviewStatusID = _fraudLabsProSettings.ReviewStatusID;
            model.RejectStatusID = _fraudLabsProSettings.RejectStatusID;
            model.Balance = _fraudLabsProSettings.Balance;

            //prepare available order statuses
            var availableStatusItems = await OrderStatus.Pending.ToSelectListAsync(false);
            foreach (var statusItem in availableStatusItems)
            {
                model.AvailableStatusLists.Add(statusItem);
            }
        }

        #endregion

        #region Methods

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        public async Task<IActionResult> Configure()
        {
            var model = new ConfigurationModel();
            await PrepareModelAsync(model);

            return View("~/Plugins/Misc.FraudLabsPro/Views/Configure.cshtml", model);
        }

        [AuthorizeAdmin]
        [Area(AreaNames.Admin)]
        [HttpPost, ActionName("Configure")]
        [FormValueRequired("save")]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!ModelState.IsValid)
                return RedirectToAction("Configure");

            //set API key
            _fraudLabsProSettings.ApiKey = model.ApiKey;
            await _settingService.SaveSettingAsync(_fraudLabsProSettings, x => x.ApiKey, clearCache: false);

            //set Approve status
            _fraudLabsProSettings.ApproveStatusID = model.ApproveStatusID;
            await _settingService.SaveSettingAsync(_fraudLabsProSettings, x => x.ApproveStatusID, clearCache: false);

            //set Review status
            _fraudLabsProSettings.ReviewStatusID = model.ReviewStatusID;
            await _settingService.SaveSettingAsync(_fraudLabsProSettings, x => x.ReviewStatusID, clearCache: false);

            //set Reject status
            _fraudLabsProSettings.RejectStatusID = model.RejectStatusID;
            await _settingService.SaveSettingAsync(_fraudLabsProSettings, x => x.RejectStatusID, clearCache: false);

            //now clear settings cache
            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return RedirectToAction("Configure");
        }

        #endregion

    }
}

Nop.Plugin.Misc.FraudLabsPro/Views/Configure.cshtml
@model Nop.Plugin.Misc.FraudLabsPro.Models.ConfigurationModel

@{
    Layout = "_ConfigurePlugin";

    var balanceStr = T("Plugins.Misc.FraudLabsPro.Fields.Balance.Unknown").ToString();
    if (!string.IsNullOrEmpty(Model.Balance))
    {
        balanceStr = Model.Balance;
    }
}

<form asp-controller="FraudLabsPro" asp-action="Configure" method="post">
    <div class="card card-default">
        <div class="card-body">
            <p>
                You can sign up for a free API key at  <a href="@FraudLabsProDefaults.FraudLabsProUpgrageUrl" target='_blank'>FraudLabs Pro.</a>
            </p>
            <p>
                To display the secured seal, make sure that the FraudLabs Pro widget is activated on the page
                <a href="@Url.Content("~/Admin/Widget/List/")">Widgets.</a>
            </p>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="ApiKey" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="ApiKey" />
                    <span asp-validation-for="ApiKey"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="ApproveStatusID" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="ApproveStatusID" asp-items="Model.AvailableStatusLists" />
                    <span asp-validation-for="ApproveStatusID"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="ReviewStatusID" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="ReviewStatusID" asp-items="Model.AvailableStatusLists" />
                    <span asp-validation-for="ReviewStatusID"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="RejectStatusID" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="RejectStatusID" asp-items="Model.AvailableStatusLists" />
                    <span asp-validation-for="RejectStatusID"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-3">
                    <nop-label asp-for="Balance" />
                </div>
                <div class="col-md-9">
                    <div class="form-text-row">@balanceStr (<a href="@FraudLabsProDefaults.FraudLabsProUpgrageUrl" target="_blank">@T("Plugins.Misc.FraudLabsPro.Fields.Balance.Upgrade")</a>)</div>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-9 offset-md-3">
                    <input type="submit" name="save" class="btn btn-primary" value="@T("Admin.Common.Save")" />
                </div>
            </div>
        </div>
    </div>
</form>

Nop.Plugin.Misc.FraudLabsPro/Views/PublicInfo.cshtml
@model Nop.Plugin.Misc.FraudLabsPro.Models.PublicInfoModel
<div class="buttons" id="fraudlabspro-buttons-container">
    <a href="@Model.HrefUrl" target="_blank">
        <img style="border:none;" alt="FraudLabs Pro Prevents Fraud for Digital Businesses" src="@Model.LinkSrc">
    </a>
</div>